// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniCoop.Infrastructure.Migrations
{
    [DbContext(typeof(MiniCoopDbContext))]
    [Migration("20260129030935_InitAllTables")]
    partial class InitAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Member", b =>
                {
                    b.Property<string>("MemberNo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MemberNo");

                    b.ToTable("members");

                    b.HasData(
                        new
                        {
                            MemberNo = "M0001",
                            AccountBalance = 5000m,
                            FullName = "สมชาย ใจดี",
                            IdCard = "1103700000011",
                            OpenDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            MemberNo = "M0002",
                            AccountBalance = 12000m,
                            FullName = "สมหญิง ใจงาม",
                            IdCard = "1103700000022",
                            OpenDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            MemberNo = "M0003",
                            AccountBalance = 3000m,
                            FullName = "วิชัย รุ่งเรือง",
                            IdCard = "1103700000033",
                            OpenDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            MemberNo = "M0004",
                            AccountBalance = 8000m,
                            FullName = "สายฝน แสงดาว",
                            IdCard = "1103700000044",
                            OpenDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            MemberNo = "M0005",
                            AccountBalance = 15000m,
                            FullName = "มนตรี กล้าหาญ",
                            IdCard = "1103700000055",
                            OpenDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            MemberNo = "M0006",
                            AccountBalance = 2000m,
                            FullName = "จันทร์เพ็ญ สุขใจ",
                            IdCard = "1103700000066",
                            OpenDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "add",
                            IsActive = true,
                            Name = "ฝากเงิน",
                            OrderNo = 1,
                            Path = "Deposit",
                            RequiredRole = "User",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Icon = "remove",
                            IsActive = true,
                            Name = "ถอนเงิน",
                            OrderNo = 2,
                            Path = "Withdraw",
                            RequiredRole = "User",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 3,
                            Icon = "list",
                            IsActive = true,
                            Name = "ประวัติ",
                            OrderNo = 3,
                            Path = "Transactions",
                            RequiredRole = "User",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 4,
                            Icon = "person",
                            IsActive = true,
                            Name = "ข้อมูลสมาชิก",
                            OrderNo = 4,
                            Path = "Members",
                            RequiredRole = "User",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 5,
                            Icon = "people",
                            IsActive = true,
                            Name = "จัดการผู้ใช้",
                            OrderNo = 5,
                            Path = "Users",
                            RequiredRole = "Admin",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 6,
                            Icon = "settings",
                            IsActive = true,
                            Name = "ตั้งค่าระบบ",
                            OrderNo = 6,
                            Path = "Settings",
                            RequiredRole = "Admin",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.MenuRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("menu_roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuId = 1,
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            MenuId = 2,
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            MenuId = 3,
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            MenuId = 4,
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            MenuId = 5,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 6,
                            MenuId = 6,
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Transaction", b =>
                {
                    b.Property<string>("MemberNo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("MemberNo", "SeqNo");

                    b.HasIndex("UsersId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            MemberNo = "M0001",
                            SeqNo = 1,
                            Amount = 5000m,
                            BalanceAfter = 5000m,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "เปิดบัญชี",
                            TransactionDate = new DateTime(2025, 1, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0001",
                            SeqNo = 2,
                            Amount = 1000m,
                            BalanceAfter = 4000m,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ถอนเงิน",
                            TransactionDate = new DateTime(2025, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "WDL"
                        },
                        new
                        {
                            MemberNo = "M0002",
                            SeqNo = 1,
                            Amount = 8000m,
                            BalanceAfter = 8000m,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ฝากครั้งแรก",
                            TransactionDate = new DateTime(2025, 1, 6, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0002",
                            SeqNo = 2,
                            Amount = 3000m,
                            BalanceAfter = 5000m,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ถอนเงิน",
                            TransactionDate = new DateTime(2025, 1, 12, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "WDL"
                        },
                        new
                        {
                            MemberNo = "M0003",
                            SeqNo = 1,
                            Amount = 12000m,
                            BalanceAfter = 12000m,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "เปิดบัญชี",
                            TransactionDate = new DateTime(2025, 1, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0003",
                            SeqNo = 2,
                            Amount = 2000m,
                            BalanceAfter = 10000m,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ถอนเงิน",
                            TransactionDate = new DateTime(2025, 1, 15, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "WDL"
                        },
                        new
                        {
                            MemberNo = "M0004",
                            SeqNo = 1,
                            Amount = 3000m,
                            BalanceAfter = 3000m,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ฝากเงิน",
                            TransactionDate = new DateTime(2025, 1, 8, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0004",
                            SeqNo = 2,
                            Amount = 2000m,
                            BalanceAfter = 5000m,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ฝากเพิ่ม",
                            TransactionDate = new DateTime(2025, 1, 18, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0005",
                            SeqNo = 1,
                            Amount = 15000m,
                            BalanceAfter = 15000m,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "เปิดบัญชี",
                            TransactionDate = new DateTime(2025, 1, 9, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0005",
                            SeqNo = 2,
                            Amount = 5000m,
                            BalanceAfter = 10000m,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ถอนเงิน",
                            TransactionDate = new DateTime(2025, 1, 20, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "WDL"
                        },
                        new
                        {
                            MemberNo = "M0006",
                            SeqNo = 1,
                            Amount = 4000m,
                            BalanceAfter = 4000m,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ฝากเงิน",
                            TransactionDate = new DateTime(2025, 1, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "DEP"
                        },
                        new
                        {
                            MemberNo = "M0006",
                            SeqNo = 2,
                            Amount = 1000m,
                            BalanceAfter = 3000m,
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "ถอนเงิน",
                            TransactionDate = new DateTime(2025, 1, 22, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "WDL"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$1heyANQHqpa3hrQV9/3c9eVA0uS.yewrl8Bo7wjPnwqDix5sm3haO",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Staff User",
                            PasswordHash = "$2a$11$ueHqS0hMvFVv.hDaDUj05ut2YwsX3R9FToBM56QY6jrhZYVjlEnGK",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.MenuRole", b =>
                {
                    b.HasOne("MiniCoop.Infrastructure.Entities.Menu", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Transaction", b =>
                {
                    b.HasOne("MiniCoop.Infrastructure.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCoop.Infrastructure.Entities.Users", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UsersId");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Menu", b =>
                {
                    b.Navigation("MenuRoles");
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.Users", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
