// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniCoop.Infrastructure.Migrations
{
    [DbContext(typeof(MiniCoopDbContext))]
    [Migration("20260203062536_InitAllTables")]
    partial class InitAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiniCoop.Domain.Entities.APPLICATION", b =>
                {
                    b.Property<int>("APPLICATION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("APPLICATION_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("APPLICATION_ID"));

                    b.Property<string>("APPLICATION_CODE")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("APPLICATION_CODE");

                    b.Property<string>("APPLICATION_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("APPLICATION_NAME");

                    b.Property<string>("ICON")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ICON");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("ORDER_NO")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NO");

                    b.HasKey("APPLICATION_ID");

                    b.ToTable("APPLICATION");

                    b.HasData(
                        new
                        {
                            APPLICATION_ID = 1,
                            APPLICATION_CODE = "Member",
                            APPLICATION_NAME = "ระบบสมาชิก",
                            ICON = "fa-solid fa-users",
                            IS_ACTIVE = true,
                            ORDER_NO = 1
                        },
                        new
                        {
                            APPLICATION_ID = 2,
                            APPLICATION_CODE = "Deposit",
                            APPLICATION_NAME = "ระบบเงินฝาก",
                            ICON = "fa-solid fa-piggy-bank",
                            IS_ACTIVE = true,
                            ORDER_NO = 2
                        });
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.DEPOSITMASTER", b =>
                {
                    b.Property<string>("ACCOUNT_NO")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<decimal>("BALANCE")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BALANCE");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("MEMBER_NO")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MEMBER_NO");

                    b.Property<DateTime>("OPEN_DATE")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OPEN_DATE");

                    b.HasKey("ACCOUNT_NO");

                    b.HasIndex("MEMBER_NO");

                    b.ToTable("DEPOSITMASTER");

                    b.HasData(
                        new
                        {
                            ACCOUNT_NO = "0000000001",
                            BALANCE = 5000m,
                            IS_ACTIVE = true,
                            MEMBER_NO = "M001",
                            OPEN_DATE = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ACCOUNT_NO = "0000000002",
                            BALANCE = 12000m,
                            IS_ACTIVE = true,
                            MEMBER_NO = "M002",
                            OPEN_DATE = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ACCOUNT_NO = "0000000003",
                            BALANCE = 3000m,
                            IS_ACTIVE = true,
                            MEMBER_NO = "M003",
                            OPEN_DATE = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.MENUGROUP", b =>
                {
                    b.Property<int>("MENU_GROUP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MENU_GROUP_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MENU_GROUP_ID"));

                    b.Property<int>("APPLICATION_ID")
                        .HasColumnType("int")
                        .HasColumnName("APPLICATION_ID");

                    b.Property<string>("APPLICATION_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("APPLICATION_NAME");

                    b.Property<string>("ICON")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ICON");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("ORDER_NO")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NO");

                    b.HasKey("MENU_GROUP_ID");

                    b.HasIndex("APPLICATION_ID");

                    b.ToTable("MENUGROUP");

                    b.HasData(
                        new
                        {
                            MENU_GROUP_ID = 1,
                            APPLICATION_ID = 1,
                            APPLICATION_NAME = "ข้อมูลสมาชิก",
                            ICON = "fa-solid fa-id-card",
                            IS_ACTIVE = true,
                            ORDER_NO = 1
                        },
                        new
                        {
                            MENU_GROUP_ID = 2,
                            APPLICATION_ID = 1,
                            APPLICATION_NAME = "รายงานสมาชิก",
                            ICON = "fa-solid fa-file-lines",
                            IS_ACTIVE = true,
                            ORDER_NO = 2
                        },
                        new
                        {
                            MENU_GROUP_ID = 3,
                            APPLICATION_ID = 2,
                            APPLICATION_NAME = "บัญชีเงินฝาก",
                            ICON = "fa-solid fa-book",
                            IS_ACTIVE = true,
                            ORDER_NO = 1
                        },
                        new
                        {
                            MENU_GROUP_ID = 4,
                            APPLICATION_ID = 2,
                            APPLICATION_NAME = "รายงานเงินฝาก",
                            ICON = "fa-solid fa-chart-line",
                            IS_ACTIVE = true,
                            ORDER_NO = 2
                        });
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.MENUS", b =>
                {
                    b.Property<int>("MENU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MENU_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MENU_ID"));

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("MENU_GROUP_ID")
                        .HasColumnType("int")
                        .HasColumnName("MENU_GROUP_ID");

                    b.Property<string>("MENU_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MENU_NAME");

                    b.Property<int>("ORDER_NO")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NO");

                    b.Property<string>("PATH")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PATH");

                    b.HasKey("MENU_ID");

                    b.HasIndex("MENU_GROUP_ID");

                    b.ToTable("MENUS");

                    b.HasData(
                        new
                        {
                            MENU_ID = 1,
                            IS_ACTIVE = true,
                            MENU_GROUP_ID = 1,
                            MENU_NAME = "ทะเบียนสมาชิก",
                            ORDER_NO = 1,
                            PATH = "List"
                        },
                        new
                        {
                            MENU_ID = 2,
                            IS_ACTIVE = true,
                            MENU_GROUP_ID = 1,
                            MENU_NAME = "เพิ่มสมาชิก",
                            ORDER_NO = 2,
                            PATH = "Create"
                        },
                        new
                        {
                            MENU_ID = 3,
                            IS_ACTIVE = true,
                            MENU_GROUP_ID = 1,
                            MENU_NAME = "แก้ไขสมาชิก",
                            ORDER_NO = 3,
                            PATH = "Edit"
                        },
                        new
                        {
                            MENU_ID = 4,
                            IS_ACTIVE = true,
                            MENU_GROUP_ID = 3,
                            MENU_NAME = "เปิดบัญชีเงินฝาก",
                            ORDER_NO = 1,
                            PATH = "Open"
                        },
                        new
                        {
                            MENU_ID = 5,
                            IS_ACTIVE = true,
                            MENU_GROUP_ID = 3,
                            MENU_NAME = "ฝากเงิน",
                            ORDER_NO = 2,
                            PATH = "In"
                        },
                        new
                        {
                            MENU_ID = 6,
                            IS_ACTIVE = true,
                            MENU_GROUP_ID = 3,
                            MENU_NAME = "ถอนเงิน",
                            ORDER_NO = 3,
                            PATH = "Out"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.MEMBERMASTER", b =>
                {
                    b.Property<string>("MEMBER_NO")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MEMBER_NO");

                    b.Property<string>("FULL_NAME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("ID_CARD")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("ID_CARD");

                    b.Property<DateTime>("OPEN_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("MEMBER_NO");

                    b.ToTable("MEMBERMASTER");

                    b.HasData(
                        new
                        {
                            MEMBER_NO = "M001",
                            FULL_NAME = "สมชาย ใจดี",
                            ID_CARD = "1103700000011",
                            OPEN_DATE = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            STATUS = "ACTIVE"
                        },
                        new
                        {
                            MEMBER_NO = "M002",
                            FULL_NAME = "สมหญิง รวยดี",
                            ID_CARD = "1103700000022",
                            OPEN_DATE = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            STATUS = "ACTIVE"
                        },
                        new
                        {
                            MEMBER_NO = "M003",
                            FULL_NAME = "วิชัย ประหยัด",
                            ID_CARD = "1103700000033",
                            OPEN_DATE = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            STATUS = "ACTIVE"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.TRANSACTION", b =>
                {
                    b.Property<string>("ACCOUNT_NO")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ACCOUNT_NO");

                    b.Property<int>("SEQ_NO")
                        .HasColumnType("int")
                        .HasColumnName("SEQ_NO");

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<decimal>("BALANCE_AFTER")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BALANCE_AFTER");

                    b.Property<DateTime?>("CREATED_AT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("REMARK")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("REMARK");

                    b.Property<DateTime>("TRANSACTION_DATE")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TRANSACTION_DATE");

                    b.Property<string>("TRANSACTION_TYPE")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("TRANSACTION_TYPE");

                    b.Property<int?>("USERSID")
                        .HasColumnType("int");

                    b.HasKey("ACCOUNT_NO", "SEQ_NO");

                    b.HasIndex("USERSID");

                    b.ToTable("TRANSACTION");

                    b.HasData(
                        new
                        {
                            ACCOUNT_NO = "0000000001",
                            SEQ_NO = 1,
                            AMOUNT = 5000m,
                            BALANCE_AFTER = 5000m,
                            TRANSACTION_DATE = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TRANSACTION_TYPE = "DEP"
                        },
                        new
                        {
                            ACCOUNT_NO = "0000000002",
                            SEQ_NO = 1,
                            AMOUNT = 12000m,
                            BALANCE_AFTER = 12000m,
                            TRANSACTION_DATE = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TRANSACTION_TYPE = "DEP"
                        },
                        new
                        {
                            ACCOUNT_NO = "0000000003",
                            SEQ_NO = 1,
                            AMOUNT = 3000m,
                            BALANCE_AFTER = 3000m,
                            TRANSACTION_DATE = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TRANSACTION_TYPE = "DEP"
                        });
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.USERS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CREATED_AT")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("FULL_NAME")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("PASSWORD_HASH")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("ROLE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("ID");

                    b.ToTable("USERS");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CREATED_AT = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FULL_NAME = "System Admin",
                            PASSWORD_HASH = "$2a$11$3ozhA7tOFeQrgFDJtk5GBuQLO.NxRSKMWewa889QjyoGyL92oW90m",
                            ROLE = "Admin",
                            USERNAME = "admin"
                        },
                        new
                        {
                            ID = 2,
                            CREATED_AT = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FULL_NAME = "Staff User",
                            PASSWORD_HASH = "$2a$11$vVNwQwIDX6cN53SuXhjSIOnFyCZRFKh3iJFkny8T6HMsbTdikVMDS",
                            ROLE = "Staff",
                            USERNAME = "staff"
                        });
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.DEPOSITMASTER", b =>
                {
                    b.HasOne("MiniCoop.Infrastructure.Entities.MEMBERMASTER", "MEMBER")
                        .WithMany()
                        .HasForeignKey("MEMBER_NO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MEMBER");
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.MENUGROUP", b =>
                {
                    b.HasOne("MiniCoop.Domain.Entities.APPLICATION", "APPLICATION")
                        .WithMany("MenuGroups")
                        .HasForeignKey("APPLICATION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APPLICATION");
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.MENUS", b =>
                {
                    b.HasOne("MiniCoop.Domain.Entities.MENUGROUP", "MENUGROUP")
                        .WithMany("Menus")
                        .HasForeignKey("MENU_GROUP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MENUGROUP");
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.TRANSACTION", b =>
                {
                    b.HasOne("MiniCoop.Domain.Entities.DEPOSITMASTER", "DEPOSITMASTER")
                        .WithMany()
                        .HasForeignKey("ACCOUNT_NO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniCoop.Infrastructure.Entities.USERS", null)
                        .WithMany("TRANSACTIONS")
                        .HasForeignKey("USERSID");

                    b.Navigation("DEPOSITMASTER");
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.APPLICATION", b =>
                {
                    b.Navigation("MenuGroups");
                });

            modelBuilder.Entity("MiniCoop.Domain.Entities.MENUGROUP", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("MiniCoop.Infrastructure.Entities.USERS", b =>
                {
                    b.Navigation("TRANSACTIONS");
                });
#pragma warning restore 612, 618
        }
    }
}
